# Generated by Django 2.1.2 on 2019-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='t_publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(on_delete=None, to='book_management_system.Publisher'),
        ),
    ]
