# Generated by Django 2.1.2 on 2019-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management_system', '0002_auto_20191205_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='无地址', max_length=128),
        ),
    ]
