# Generated by Django 2.1.2 on 2019-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management_system', '0003_publisher_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255, unique=True)),
                ('book', models.ManyToManyField(to='book_management_system.Book')),
            ],
            options={
                'db_table': 't_author',
            },
        ),
    ]
